### ISSUE TITLE
How to fix erorr

### ISSUE THREAD

**Issue by cmdgits** [khondokerXhasan/Vanilla-finance-BOT#2]
please fix Traceback (most recent call last):
  File "C:\Users\hieudx\Desktop\ALL_AIRDROP\Vanilla-finance-BOT\Vanilla-Finance.py", line 5, in <module>
    from bot.utils import logger
  File "C:\Users\hieudx\Desktop\ALL_AIRDROP\Vanilla-finance-BOT\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\hieudx\Desktop\ALL_AIRDROP\Vanilla-finance-BOT\bot\utils\launcher.py", line 7, in <module>
    from bot.config import settings
  File "C:\Users\hieudx\Desktop\ALL_AIRDROP\Vanilla-finance-BOT\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\hieudx\Desktop\ALL_AIRDROP\Vanilla-finance-BOT\bot\config\config.py", line 4, in <module>
    class Settings(BaseSettings):
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_model_construction.py", line 183, in __new__
    complete_model_class(
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 742, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 563, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 563, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 906, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1071, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1737, in _apply_annotations
    res = self._get_prepare_pydantic_annotations_for_known_type(source_type, tuple(annotations))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1718, in _get_prepare_pydantic_annotations_for_known_type
    res = gen(obj, annotations, self._config_wrapper.config_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hieudx\AppData\Roaming\Python\Python311\site-packages\pydantic\_internal\_std_types_schema.py", line 406, in sequence_like_prepare_pydantic_annotations
    raise ValueError('Expected sequence to have exactly 1 generic parameter')
ValueError: Expected sequence to have exactly 1 generic parameter

**Comment by khondokerXhasan** [comment]
Git pull and reinstall it
